In [17]:
import numpy as np

an_array = np.array([3, 33, 333])

print(type(an_array))

<class 'numpy.ndarray'>


In [18]:
an_array

array([  3,  33, 333])

In [19]:
print(an_array.shape)

(3,)


In [20]:
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [21]:
an_array[0] = 888

In [22]:
an_array

array([888,  33, 333])

In [23]:
another = np.array([[11,12,13],[21,22,23]])

In [24]:
print(another)

print("The shape is 2 rows, 3 columns:", another.shape) #rows x columns

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns: (2, 3)


In [25]:
print("Accessing elements [0,0], [0,1], [1,0] of the ndarray", another[0, 0], ",",another[0, 1],",", another[1, 0])

Accessing elements [0,0], [0,1], [1,0] of the ndarray 11 , 12 , 21


In [26]:
import numpy as np
#create a 2x2 array of zeros
ex1 = np.zeros((2,2))

In [27]:
print(ex1)

[[0. 0.]
 [0. 0.]]


In [28]:
ex2 = np.full((2,2),9.0)

In [29]:
print(ex2)

[[9. 9.]
 [9. 9.]]


In [30]:
ex3 = np.eye(2,2)
print(ex3)
print(ex3.shape)

[[1. 0.]
 [0. 1.]]
(2, 2)


In [31]:
ex4 = np.ones((3,2))
print(ex4)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [32]:
ex5 = np.random.random((2,2))
print(ex5)

[[0.60412017 0.07490184]
 [0.82469937 0.44093944]]


# Slicing

In [40]:
import numpy as np

# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [37]:
a_slice = an_array[:2,1:3]
a_slice

array([[12, 13],
       [22, 23]])

In [38]:
an_array[0,1] = 1000

In [39]:
a_slice #Note that a_slice changes when an_array changes because a_slice is a pointer to part of an_array.

array([[1000,   13],
       [  22,   23]])

In [45]:
# To create a copy of the array as a_slice do this:
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
a_copy = np.array(an_array[:2,1:3])
print(a_copy)
an_array[0,1] = 1000
print(a_copy)
# Note the copy isn't changed when the original array changes.

[[12 13]
 [22 23]]
[[12 13]
 [22 23]]


In [47]:
an_array

array([[  11, 1000,   13,   14],
       [  21,   22,   23,   24],
       [  31,   32,   33,   34]])

In [48]:
new_array = an_array[:2,]
new_array

array([[  11, 1000,   13,   14],
       [  21,   22,   23,   24]])

In [50]:
# create a 3x2 array
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [52]:
filtered = (an_array > 15)
filtered

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [54]:
print(an_array[filtered])

[21 22 31 32]


In [55]:
an_array[an_array > 15] #single step to filter

array([21, 22, 31, 32])

In [58]:
an_array[(an_array > 20) & (an_array < 30)]

array([21, 22])

In [59]:
an_array[an_array%2 == 0] +=100

In [60]:
an_array

array([[ 11, 112],
       [ 21, 122],
       [ 31, 132]])

In [61]:
# setup a random 2 x 4 matrix
arr = 10 * np.random.randn(2,5)
print(arr)

[[  6.72558401  -5.00880634 -12.63309925  -4.29574353  -6.283173  ]
 [ -2.25138078  -3.77743695  -7.70483167  10.40852534   0.58398914]]


In [62]:
# compute the mean for all elements
print(arr.mean())

-2.423637302688749


In [63]:
# compute the means by row
print(arr.mean(axis = 1))

[-4.29904762 -0.54822698]


In [67]:
# compute the medians
print(np.median(arr, axis = 1))

[-5.00880634 -2.25138078]


In [68]:
# compute the medians
print(np.mean(arr, axis = 1))

[-4.29904762 -0.54822698]
